AWSTemplateFormatVersion:  2010-09-09 
Description: A sample VPC
Resources:
    MyCFVPC:
      Type:  AWS::EC2::VPC 
      Properties: 
           CidrBlock:  172.172.0.0/16 
           InstanceTenancy:  default 
           Tags:
            - Key:  Name 
              Value:  MyCFVPC 
    MyPrivateSubnetVPC  :
       Type: AWS::EC2::Subnet
       Properties:
           CidrBlock:  172.172.10.0/24 
           VpcId:
                Ref: MyCFVPC
           Tags:
            - Key:  Name  
              Value:  MyPrivateSubnetVPC 
    MyRTPrivateSub:
        Type:   AWS::EC2::RouteTable
        Properties:
             VpcId:
                  Ref: MyCFVPC
              Tags:
               - Key: Name
                 Value: MyRTPrivateSub